### ISSUE TITLE
Add sec-api.io as data source

### ISSUE THREAD

**Issue by janlukasschroeder** [EliteQuant/EliteQuant#9]
Suggest adding the SEC EDGAR API ([sec-api.io](https://sec-api.io)) to the section "Data Source" to query or stream company filings on SEC EDGAR. Includes 10-K, 10-Qs, 4/3/5 insider trading forms, 8-K and all the other 150 filing types.

**Comment by EliteQuant** [comment]
Thanks, interesting.
